# Generated by Django 5.1.1 on 2024-10-10 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='size',
            field=models.CharField(choices=[('Tiny', 'Tiny'), ('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], max_length=10),
        ),
        migrations.AlterField(
            model_name='dog',
            name='breed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dogapi.breed'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='favoritefood',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='dog',
            name='favoritetoy',
            field=models.CharField(max_length=50),
        ),
    ]
